using IdaParser.CppParser;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace IdaParser.TestConsole
{
    internal static class Program
    {
        private static async Task Main()
        {
            const string path = @"C:\Maplestory95.exe.h";
            var parser = new Parser();

            //var results = parser.SearchForStructInHeaderFile(path, "struct CItemInfo::INCLEVELITEM");
            //foreach(var rslt in results)
            //Console.WriteLine("Idx: {0} Word: {1}", rslt.Index, rslt.Word);

            List<Tuple<int, string>> results = new();
            string[] toSearchFor = { 
                "struct CItemInfo::SETITEMINFO",
                "struct CItemInfo::PETFOODITEM" };

            foreach (var str in toSearchFor)
                results.AddRange(parser.SearchForStructInHeaderFile2(path, str).ToList());

            if (!results.Any()) return;

            List<string> linesToWrite = new();
            const string openComment = "/*";
            var metaInfo = "* Autogenerated by IdaParser on: " + DateTime.Now;
            const string closeComment = "*/";

            linesToWrite.Add(openComment);
            linesToWrite.Add(metaInfo);
            linesToWrite.Add(closeComment);
            linesToWrite.AddRange(results.Select(rslt => rslt.Item2));

            foreach (var line in linesToWrite)
                Console.WriteLine("Line: {0}", line);

            await File.WriteAllLinesAsync(@"C:\test.txt", linesToWrite);

            var defFile = new DefinitionFile();
            defFile.Parse(@"C:\Users\Bia\source\repos\MaplestoryV95.1\Classes\Definition\CItemInfo.h");

            foreach (var @class in defFile.classes)
                Console.WriteLine("{0} at Line: {1}", @class, @class.LineIndex);
            foreach (var @struct in defFile.structures)
                Console.WriteLine("{0} at Line: {1}", @struct, @struct.LineIndex);
            foreach (var memberVar in defFile.classes.First().memberVar)
                Console.WriteLine("Var Type: {0} Name: {1}", memberVar.DataType, memberVar.Name);
        }
    }
}
